### ISSUE TITLE
No elevation for Hamburg

### ISSUE THREAD

**Issue by FlorianWilhelm** [tkrajina/srtm.py#12]
Somehow this magical point ``GPXTrackPoint(53.51195, 9.97416666667)`` gets an elevation of ``None`` although it is close to Hamburg, Germany. Varying the latitude/longitude a bit works. Is this a rounding error somewhere in srtm.py?

**Comment by tkrajina** [comment]
That's why I added the API to create sample images from the data. Try this

geo_elevation_data = mod_srtm.get_data()

    geo_elevation_data = mod_srtm.get_data()

    #53.51195, 9.97416666667
    image = geo_elevation_data.get_image((400, 400), (53, 54), (9, 10), 100)
    image.save('aaa.png')

This is the result:

![aaa](https://cloud.githubusercontent.com/assets/379243/13523136/e7421b08-e1f3-11e5-98b6-b778a973c469.png)

The white dots represents areas without SRTM data.

I don't know why that is, but it's similar for some flat areas around Venezia, too. 

I tried to force using only SRTM1 and it looks like there are no data at all for that square, maybe something is wrong with that. But SRTM3 is definitely missing some elevations.

**Comment by FlorianWilhelm** [comment]
Thanks for the fast explanation. I found that behaviour when I used ``add_elevations(gpx_obj, smooth=True)``. In this case if there is a start or end point point with elevation ``None`` the code breaks at an assertion statement. It really seems that the height map of the moon is more complete than what we have on earth:-)
But I think breaking is okay in this case. So we can close this I guess.
